
apiVersion: v1
kind: Pod
metadata:
  name: kaniko
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:latest
    args: ["--dockerfile=/workspace/test-data/Dockerfile",
            "--context=dir://workspace/test-data",
            "--destination=registry.docker-registry.svc.cluster.local/test-data:latest"] 
    volumeMounts:
      - name: dockerfile-storage
        mountPath: /workspace
  restartPolicy: Never
  volumes:
    - name: dockerfile-storage
      hostPath:
        path: /tmp/kaniko
